# example netlify.toml
[build]
  command = "astro build"
  functions = "netlify/functions"
  publish = "dist"

[[plugins]] 
  package = "netlify-plugin-cypress"

  [plugins.inputs.postBuild]
    enable = true
  
  [plugin.inputs]
    enable = false
[[redirects]]
  from = "/oopswediditagain.com"
  to = "/oopswediditagain/it"

  status = 301

  # By default, redirects won’t be applied if there’s a file with the same
  # path as the one defined in the `from` property. Setting `force` to `true`
  # will make the redirect rule take precedence over any existing files.
  force = true

  # Redirect based on conditions including browser language, geolocation,
  # identity role, and/or cookie presence.
  conditions = {Language = ["it"], Country = ["IT"]}
